version: 0.2

env:
  parameter-store:
    PRODUCTS_TABLE: "/myapp/PRODUCTS_TABLE"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g jest
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install aws-sdk-mock --save-dev
  build:
    commands:
      - echo "Running tests and zipping Lambda functions..."
      - mkdir -p dist
      - |
        for func in functions/*; do
          if [ -d "$func" ]; then
            func_name=$(basename "$func")
            echo "Processing $func_name..."
            
            # Run tests for this function
            PRODUCTS_TABLE=$PRODUCTS_TABLE jest tests/${func_name}.test.js
            
            if [ $? -eq 0 ]; then
              echo "Tests passed for $func_name. Zipping and preparing for deployment..."
              (
                cd "$func" || exit 1
                zip -r "../../dist/$func_name.zip" index.js ../../node_modules
              )
              if [ $? -ne 0 ]; then
                echo "Error zipping $func_name"
                exit 1
              fi
              echo "$func_name" >> ../successful_tests.txt
            else
              echo "Tests failed for $func_name. Skipping deployment."
            fi
          fi
        done
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp dist s3://${S3_BUCKET_NAME} --recursive
      - echo "Updating Lambda functions..."
      - |
        if [ -f successful_tests.txt ]; then
          while IFS= read -r func_name
          do
            echo "Updating $func_name..."
            # Create IAM role for Lambda
            ROLE_NAME="${func_name}-role"
            ROLE_ARN=$(aws iam create-role --role-name $ROLE_NAME --assume-role-policy-document '{"Version": "2012-10-17","Statement": [{"Effect": "Allow","Principal": {"Service": "lambda.amazonaws.com"},"Action": "sts:AssumeRole"}]}' --query 'Role.Arn' --output text)
            
            # Attach policies to the role
            aws iam attach-role-policy --role-name $ROLE_NAME --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            aws iam attach-role-policy --role-name $ROLE_NAME --policy-arn arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
            
            # Update Lambda function
            aws lambda update-function-code --function-name ${func_name} --s3-bucket ${S3_BUCKET_NAME} --s3-key ${func_name}.zip
            aws lambda update-function-configuration --function-name ${func_name} --environment "Variables={PRODUCTS_TABLE=$PRODUCTS_TABLE}" --role $ROLE_ARN
            
            if [ $? -ne 0 ]; then
              echo "Error updating Lambda function $func_name"
              exit 1
            fi
          done < successful_tests.txt
        else
          echo "No functions passed tests. Skipping deployment."
        fi

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'