version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Zipping Lambda functions..."
      - mkdir -p dist
      - for func in functions/*; do
          if [ -d "$func" ]; then
            func_name=$(basename "$func")
            echo "Processing $func_name..."
            cd "$func"
            zip -r "../../dist/$func_name.zip" index.js ../../node_modules
            cd ../..
          fi
        done
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp dist s3://${S3_BUCKET_NAME} --recursive
      - echo "Updating Lambda functions..."
      - for zip in dist/*.zip; do
          func_name=$(basename "$zip" .zip)
          aws lambda update-function-code --function-name ${func_name} --s3-bucket ${S3_BUCKET_NAME} --s3-key $(basename "$zip")
        done

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'